### ISSUE TITLE
undefined variable: media

### ISSUE THREAD

**Issue by candelariajr** [Daniel-KM/Omeka-plugin-UniversalViewer#39]
Performed a regular install on two servers. 
One works perfectly, but one gets this output, causing Universal Viewer to crash:
This happens only on PDF file types.

Notice: Undefined variable: media in /data/omeka/plugins/UniversalViewer/views/helpers/IiifManifest.php on line 285

Fatal error: Uncaught Error: Call to a member function mediaType() on null in /data/omeka/plugins/UniversalViewer/views/helpers/IiifManifest.php:285
Stack trace:
#0 /data/omeka/plugins/UniversalViewer/views/helpers/IiifManifest.php(20): UniversalViewer_View_Helper_IiifManifest->_buildManifestItem(Object(Item))
#1 /data/omeka/application/libraries/Zend/View/Abstract.php(349): UniversalViewer_View_Helper_IiifManifest->iiifManifest(Object(Item))
#2 /data/omeka/plugins/UniversalViewer/controllers/PresentationController.php(120): Zend_View_Abstract->__call(‘iiifManifest’, Array)
#3 /data/omeka/application/libraries/Zend/Controller/Action.php(516): UniversalViewer_PresentationController->itemAction()
#4 /data/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch(‘itemAction’)
#5 /data/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /data/om in /data/omeka/plugins/UniversalViewer/views/helpers/IiifManifest.php on line 285

**Comment by candelariajr** [comment]
Runaway script synced files to old version of plugin.
